In [1]:
import pandas as pd

In [4]:
df_logs = pd.read_csv("device_health_logs.csv")
df_device = pd.read_csv("device_info.csv")
df_incident = pd.read_csv("incident_logs.csv")

In [5]:
df_logs["CPU_Usage"].isnull().sum()

np.int64(31)

In [6]:
df_logs["CPU_Usage"].fillna(df_logs["CPU_Usage"].median(), inplace=True)

In [7]:
df_logs.isnull().sum()

Timestamp       0
Device_ID       0
CPU_Usage       0
Memory_Usage    0
Uptime          0
Temperature     0
dtype: int64

In [8]:
df_logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Timestamp     2020 non-null   object
 1   Device_ID     2020 non-null   object
 2   CPU_Usage     2020 non-null   float64
 3   Memory_Usage  2020 non-null   int64
 4   Uptime        2020 non-null   int64
 5   Temperature   2020 non-null   int64
dtypes: float64(1), int64(3), object(2)
memory usage: 94.8+ KB

In [9]:
df_logs["Timestamp"] = pd.to_datetime(df_logs["Timestamp"], errors="coerce")

In [10]:
df_logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Timestamp     2020 non-null   datetime64[ns]
 1   Device_ID     2020 non-null   object
 2   CPU_Usage     2020 non-null   float64
 3   Memory_Usage  2020 non-null   int64
 4   Uptime        2020 non-null   int64
 5   Temperature   2020 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 94.8+ KB

In [11]:
df_logs.isnull().sum()

Timestamp       0
Device_ID       0
CPU_Usage       0
Memory_Usage    0
Uptime          0
Temperature     0
dtype: int64

In [12]:
df_logs["Device_ID"].unique()

array(['D007', 'D008', 'D011', 'D002', 'D012', 'D020', 'D004', 'D009',
       'D015', 'D018', 'D016', 'D013', 'D005', 'D001', 'D003', 'D014',
       'D019', 'D006', 'D017', 'Device_X', 'D010'], dtype=object)

In [13]:
valid_devices = df_device["Device_ID"].unique()

In [14]:
valid_devices

array(['D004', 'D002', 'D005', 'D006', 'D010', 'D019', 'D014', 'D012',
       'D003', 'D011', 'D018', 'D017', 'D008', 'D016', 'D007', 'D020',
       'D001', 'D015', 'D009', 'D013'], dtype=object)

In [15]:
df_logs = df_logs[df_logs["Device_ID"].isin(valid_devices)]

In [16]:
df_logs["Device_ID"].unique()

array(['D007', 'D008', 'D011', 'D002', 'D012', 'D020', 'D004', 'D009',
       'D015', 'D018', 'D016', 'D013', 'D005', 'D001', 'D003', 'D014',
       'D019', 'D006', 'D017', 'D010'], dtype=object)

In [52]:
df_logs.isnull().sum()

Timestamp       0
Device_ID       0
CPU_Usage       0
Memory_Usage    0
Uptime          0
Temperature     0
dtype: int64

In [18]:
df_logs.to_csv("cleaned_device_logs.csv", index=False)

In [22]:
df_device.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Device_ID     21 non-null     object
 1   Device_Type   21 non-null     object
 2   Location      21 non-null     object
 3   Install_Date  21 non-null     datetime64[ns]
 4   Status        21 non-null     object
dtypes: datetime64[ns](1), object(4)
memory usage: 972.0+ bytes

In [20]:
df_device.describe()

       Device_ID Device_Type Location Install_Date  Status
count         21          21       21           21      21
unique        20           5        7           20       2
top         D004      Switch  Chennai   2022-05-11  Active
freq           2           8        5            2      18

In [28]:
df_device["Status"].unique()

array(['Inactive', 'Active'], dtype=object)

In [31]:
df_device[df_device["Device_ID"].duplicated(keep=False)]

   Device_ID Device_Type Location Install_Date    Status
0       D004      Switch  Chennai   2022-05-11  Inactive
17      D004      Switch  Chennai   2022-05-11  Inactive

In [33]:
df_device[df_device.duplicated()]

   Device_ID Device_Type Location Install_Date    Status
17      D004      Switch  Chennai   2022-05-11  Inactive

In [37]:
df_device[df_device["Device_ID"].duplicated(keep=False)]

Empty DataFrame
Columns: [Device_ID, Device_Type, Location, Install_Date, Status]
Index: []

In [44]:
df_incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Incident_ID  300 non-null    object
 1   Device_ID    300 non-null    object
 2   Issue_Type   300 non-null    object
 3   Severity     300 non-null    object
 4   Start_Time   300 non-null    datetime64[ns]
 5   End_Time     300 non-null    object
dtypes: datetime64[ns](1), object(5)
memory usage: 14.2+ KB

In [42]:
(df_incident["End_Time"] < df_incident["Start_Time"]).sum()

np.int64(0)

In [45]:
df_incident["Start_Time"] = pd.to_datetime(df_incident["Start_Time"])

In [49]:
df_incident["End_Time"]=pd.to_datetime(df_incident["Start_Time"])

In [59]:
df_incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Incident_ID  300 non-null    object
 1   Device_ID    300 non-null    object
 2   Issue_Type   300 non-null    object
 3   Severity     300 non-null    object
 4   Start_Time   300 non-null    datetime64[ns]
 5   End_Time     300 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(4)
memory usage: 14.2+ KB

In [61]:
df_incident = df_incident[df_incident["End_Time"] >= df_incident["Start_Time"]]

In [62]:
df_incident["Downtime_Hours"] = (
    df_incident["End_Time"] - df_incident["Start_Time"]
).dt.total_seconds() / 3600

In [65]:
df_incident

,Incident_ID,Device_ID,Issue_Type,Severity,Start_Time,End_Time,Downtime_Hours
0,INC000,D008,Overheating,Medium,2025-06-03 16:00:00,2025-06-03 16:00:00,0.0
1,INC001,D014,High CPU,Low,2025-08-20 04:00:00,2025-08-20 04:00:00,0.0
2,INC002,D005,Overheating,Medium,2025-07-14 11:00:00,2025-07-14 11:00:00,0.0
3,INC003,D019,Network Failure,Low,2025-06-18 23:00:00,2025-06-18 23:00:00,0.0
4,INC004,D009,High CPU,Low,2025-07-30 22:00:00,2025-07-30 22:00:00,0.0
...,...,...,...,...,...,...,...
295,INC295,D015,High CPU,Critical,2025-06-06 02:00:00,2025-06-06 02:00:00,0.0
296,INC296,D012,High CPU,Medium,2025-07-17 02:00:00,2025-07-17 02:00:00,0.0
297,INC297,D007,Overheating,High,2025-06-18 19:00:00,2025-06-18 19:00:00,0.0
298,INC298,D011,High CPU,High,2025-08-05 11:00:00,2025-08-05 11:00:00,0.0
299,INC299,D009,Overheating,Low,2025-08-02 03:00:00,2025-08-02 03:00:00,0.0

In [68]:
(df_incident["Start_Time"] == df_incident["End_Time"]).sum()

np.int64(300)

In [70]:
df_incident = pd.read_csv("incident_logs.csv")

In [72]:
df_incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Incident_ID  300 non-null    object
 1   Device_ID    300 non-null    object
 2   Issue_Type   300 non-null    object
 3   Severity     300 non-null    object
 4   Start_Time   300 non-null    object
 5   End_Time     300 non-null    object
dtypes: object(6)
memory usage: 14.2+ KB

In [74]:
df_incident["Start_Time"] = pd.to_datetime(df_incident["Start_Time"])

In [76]:
df_incident["End_Time"] = pd.to_datetime(df_incident["End_Time"])

In [77]:
df_incident[["Start_Time", "End_Time"]].head()

           Start_Time            End_Time
0 2025-06-03 16:00:00 2025-06-03 21:00:00
1 2025-08-20 04:00:00 2025-08-20 08:00:00
2 2025-07-14 11:00:00 2025-07-14 14:00:00
3 2025-06-18 23:00:00 2025-06-19 04:00:00
4 2025-07-30 22:00:00 2025-07-30 23:00:00

In [82]:
df_incident["Downtime_Hours"] = (
    df_incident["End_Time"] - df_incident["Start_Time"]
).dt.total_seconds() / 3600

In [83]:
df_incident[["Start_Time", "End_Time", "Downtime_Hours"]].head()

           Start_Time            End_Time  Downtime_Hours
0 2025-06-03 16:00:00 2025-06-03 21:00:00             5.0
1 2025-08-20 04:00:00 2025-08-20 08:00:00             4.0
2 2025-07-14 11:00:00 2025-07-14 14:00:00             3.0
3 2025-06-18 23:00:00 2025-06-19 04:00:00             5.0
4 2025-07-30 22:00:00 2025-07-30 23:00:00             1.0

In [84]:
df_incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Incident_ID     300 non-null    object
 1   Device_ID       300 non-null    object
 2   Issue_Type      300 non-null    object
 3   Severity        300 non-null    object
 4   Start_Time      300 non-null    datetime64[ns]
 5   End_Time        300 non-null    datetime64[ns]
 6   Downtime_Hours  300 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 16.5+ KB

In [90]:
df_incident.head()

,Incident_ID,Device_ID,Issue_Type,Severity,Start_Time,End_Time,Downtime_Hours
0,INC000,D008,Overheating,Medium,2025-06-03 16:00:00,2025-06-03 21:00:00,5.0
1,INC001,D014,High CPU,Low,2025-08-20 04:00:00,2025-08-20 08:00:00,4.0
2,INC002,D005,Overheating,Medium,2025-07-14 11:00:00,2025-07-14 14:00:00,3.0
3,INC003,D019,Network Failure,Low,2025-06-18 23:00:00,2025-06-19 04:00:00,5.0
4,INC004,D009,High CPU,Low,2025-07-30 22:00:00,2025-07-30 23:00:00,1.0

In [92]:
df_incident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Incident_ID     300 non-null    object
 1   Device_ID       300 non-null    object
 2   Issue_Type      300 non-null    object
 3   Severity        300 non-null    object
 4   Start_Time      300 non-null    datetime64[ns]
 5   End_Time        300 non-null    datetime64[ns]
 6   Downtime_Hours  300 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 16.5+ KB

In [93]:
df_incident.to_csv("clean_incident_logs.csv", index=False)

In [94]:
df_device.head()

  Device_ID Device_Type   Location Install_Date    Status
0      D004      Switch    Chennai   2022-05-11  Inactive
1      D002    Firewall     Mumbai   2024-11-10    Active
2      D005      Switch  Hyderabad   2024-03-16    Active
3      D006      router    Chennai   2023-04-05    Active
4      D010      Router      Delhi   2023-10-09    Active

In [96]:
df_device.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 20
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Device_ID     20 non-null     object
 1   Device_Type   20 non-null     object
 2   Location      20 non-null     object
 3   Install_Date  20 non-null     datetime64[ns]
 4   Status        20 non-null     object
dtypes: datetime64[ns](1), object(4)
memory usage: 960.0+ bytes

In [107]:
df_device["Device_Type"].unique()

array(['Switch', 'Firewall', 'Router'], dtype=object)

In [113]:
df_device["Location"].unique()

array(['Chennai', 'Mumbai', 'Hyderabad', 'Delhi', 'Bangalore'],
      dtype=object)

In [114]:
df_device["Device_Type"] = df_device["Device_Type"].str.strip().str.title()

In [115]:
df_device["Device_Type"] = df_device["Device_Type"].replace({
    "Switchh": "Switch"
})

In [116]:
df_device["Location"] = df_device["Location"].str.strip().str.title()

In [117]:
df_device.to_csv("clean_device_info.csv", index=False)